GET {{host}}/oauth/token?
    grant_type=authorization_code&
    client_id={{oauth2_client_id}}&
    client_secret={{oauth2_client_secret}}&
    redirect_uri:{{oauth2_redirect_uri}}&
    code_verifier=not-available-now&
    code={{oauth2_code}}